### ISSUE TITLE
Add .gitlab-ci.yml

### ISSUE THREAD

**Issue by William-Yeh** [softarch-school/docker-workshop-rev#2]
Need to add `.gitlab-ci.yml` file for demonstrate the CI build flow.

**Comment by 36web** [comment]
Here a working `.gitlab-ci.yml` I used to build my own docker image.
```yml
image: docker:latest
services:
  - docker:dind
variables:
  CONTAINER_VERSION_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
build:
  stage: build
  script:
    - docker build --no-cache -t $CONTAINER_VERSION_IMAGE .
    - docker tag $CONTAINER_VERSION_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_VERSION_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - tags
```
